# Secret — Variables sensibles (ADMIN_PASSWORD + APP_SECRET)
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-app.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value }}
  {{- end }}
