apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
  namespace: tp-k8s
data:
  APP_NAME: "K8s Demo Notes"
  APP_ENV: "production"
  APP_VERSION: "1.0.0"
  LOG_LEVEL: "info"
  STORAGE_PATH: "/data"
  FEATURE_UPLOAD_ENABLED: "true"
  PORT: "3000"