apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-k8s
  namespace: tp-k8s
spec:
  storageClassName: demo-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
